kind = "web"
previewPath = "/"
title = "IRONLAB - Academia"
version = "1.0.0"
id = "artifacts/ironlab"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25959

[services.development]
run = "pnpm --filter @workspace/ironlab run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ironlab", "run", "build" ]
publicDir = "artifacts/ironlab/.output/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25959"
NUXT_PORT = "25959"
